import back from "./desktop/image-header.jpg";
import logo from "./logo.svg";
import arr from "./icon-arrow-down.svg";
import hmb from "./icon-hamburger.svg";
import backm from "./mobile/image-header.jpg";
import img1 from "./desktop/image-transform.jpg";
import img2 from "./desktop/image-stand-out.jpg";
import img3 from "./desktop/image-photography.jpg";
import img4 from "./desktop/image-graphic-design.jpg";
import emily from "./image-emily.jpg";
import jennie from "./image-jennie.jpg";
import thomas from "./image-thomas.jpg";
import gallery1 from "./desktop/image-gallery-cone.jpg";
import gallery2 from "./desktop/image-gallery-orange.jpg";
import gallery3 from "./desktop/image-gallery-milkbottles.jpg";
import gallery4 from "./desktop/image-gallery-sugarcubes.jpg";
import fbicon from "./icon-facebook.svg";
import inicon from "./icon-instagram.svg";
import pinicon from "./icon-pinterest.svg";
import twicon from "./icon-twitter.svg";
import Mobilegd from "./mobile/image-graphic-design.jpg";
import Mobilept from "./mobile/image-photography.jpg";
import Mobilemilk from "./mobile/image-gallery-milkbottles.jpg";
import Mobilesc from "./mobile/image-gallery-sugar-cubes.jpg";
import Mobileor from "./mobile/image-gallery-orange.jpg";
import Mobileco from "./mobile/image-gallery-cone.jpg";

export const Background = back;
export const LogoS = logo;
export const Arrow = arr;
export const hamburger = hmb;
export const BackgroundMobil = backm;
export const Img1 = img1;
export const Img2 = img2;
export const Img3 = img3;
export const Img4 = img4;
export const Emily = emily;
export const Jennie = jennie;
export const Thomas = thomas;
export const Cone = gallery1;
export const Orange = gallery2;
export const Milkbottles = gallery3;
export const Sugercubes = gallery4;
export const facebook = fbicon;
export const instagram = inicon;
export const pinterest = pinicon;
export const twitter = twicon;
export const MobileGD = Mobilegd;
export const MobilePH = Mobilept;
export const MobileMilk = Mobilemilk;
export const MobileSc = Mobilesc;
export const MobileOr = Mobileor;
export const MobileCo = Mobileco;
